### ISSUE TITLE
How to put Progressbar

### ISSUE THREAD

**Issue by chunarakaran** [4eRTuk/audioview#13]
How to put progressbar when audio load from uri

**Comment by 4eRTuk** [comment]
Same as for local file except total length could be determined wrong (-1 for example, I think default Android MediaPlayer causes this behaviour).

See demo app for more info:
[Java code](https://github.com/4eRTuk/audioview/blob/master/app/src/main/java/com/keenfin/audioviewdemo/MainActivity.java#L33)
[XML layout](https://github.com/4eRTuk/audioview/blob/master/app/src/main/res/layout/activity_main.xml#L91)

**Comment by chunarakaran** [comment]
how to put in this code

public class AudioPlayerActivity extends AppCompatActivity  {

    String Content_id,audio_url;

    AudioView audioView;

    private ProgressDialog pDialog;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_audio_player);

        audio_url = getIntent().getStringExtra("audio_url");

        // Progress dialog
        pDialog = new ProgressDialog(this);
        pDialog.setCancelable(false);

        audioView=(AudioView)findViewById(R.id.audioview);

//        pDialog.setMessage("Please Wait...");
//        showDialog();

        try {
            audioView.setDataSource(audio_url);
            audioView.start();
        } catch (IOException e) {
            e.printStackTrace();
        }

//        hideDialog();
    }
    

    @SuppressLint("MissingSuperCall")
    @Override
    protected void onStop() {
        super.onPause();
        audioView.pause();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        audioView.pause();
    }

    private void showDialog() {
        if (!pDialog.isShowing())
            pDialog.show();
    }

    private void hideDialog() {
        if (pDialog.isShowing())
            pDialog.dismiss();
    }
}

**Comment by 4eRTuk** [comment]
I do not see your ProgressBar. Where do you want to put it and what should it do? Default AudioView has SeekBar showing current track percentage completion and allowing to seek over the track.

**Comment by chunarakaran** [comment]
Show progressbar when audio url load

**Comment by 4eRTuk** [comment]
If you download audio to local storage then it's not related question.

If you want to show progress while AudioView is preparing (it does not matter from url or local) then you could implement [AudioViewListener](https://github.com/4eRTuk/audioview/blob/master/audioview/src/main/java/com/keenfin/audioview/AudioViewListener.java) for AudioView and override onPrepared() method. Then set listener through [AudioView's setOnAudioViewListener()](https://github.com/4eRTuk/audioview/blob/master/audioview/src/main/java/com/keenfin/audioview/BaseAudioView.java#L200).

**Comment by 4eRTuk** [comment]
Closed due to inactivity
