### ISSUE TITLE
Playing next / previous track 

### ISSUE THREAD

**Issue by Ahmed-Ganna** [4eRTuk/audioview#16]
Is there any built in function that plays next / previous track programmatically in AudioView if a list of audios was provided ?

**Comment by 4eRTuk** [comment]
Yes, added [funcs to views](https://github.com/4eRTuk/audioview#usage-with-gradle). For AudioView2 it is possible to control [via service intents](https://github.com/4eRTuk/audioview#or-send-command-to-service-to-control-playback) also.
