### ISSUE TITLE
Can it stream audio from url?

### ISSUE THREAD

**Issue by akinfopark** [4eRTuk/audioview#18]

**Comment by 4eRTuk** [comment]
Yes, please see the [README](https://github.com/4eRTuk/audioview#usage-with-gradle). You need to pass Uri object to setDataSource.

**Comment by akinfopark** [comment]
This is url http://easemypay.in/jobs/admin/uploads/jobaudios/airland.mp3

audioView.setDataSource(Uri.parse("http://easemypay.in/jobs/admin/uploads/jobaudios/airland.mp3"));

The seekbar keeps loading & shows an infinity symbol at bottom right
