### ISSUE TITLE
 java.lang.IllegalStateException.android.media.MediaPlayer.getCurrentPosition

### ISSUE THREAD

**Issue by liuxuesong001** [4eRTuk/audioview#3]
customize dialog layout Dismiss error.

**Comment by andreypelipets** [comment]
when will this error be fixed?

**Comment by JDevelopes** [comment]
bro, you need to update your library. You need add try catch blocks where you put method 

mMediaPlayer.getCurrentPossition(); . I have editted your library as a module and I have added try catch blocks. It's working now.

**Comment by MyWay** [comment]
You could do a pull request, then.

**Comment by 4eRTuk** [comment]
I added try catch where possible, check it out in 1.1. Also #6 is in live!
